"use client";

type ImageExportData = {
  documentType: string;
  coreSummary: string;
  points: string[];
  generatedAt: string;
};

export default function ImageExportCard({
  cardRef,
  data,
}: {
  cardRef: React.RefObject<HTMLDivElement | null>;
  data: ImageExportData | null;
}) {
  if (!data) return null;

  return (
    <div style={{ position: "absolute", left: "-9999px", top: 0, pointerEvents: "none" }} aria-hidden="true">
      <div
        ref={cardRef}
        style={{
          width: "1200px",
          minHeight: "630px",
          padding: "44px",
          background: "linear-gradient(180deg, #ffffff 0%, #f8fbff 100%)",
          borderRadius: "20px",
          boxShadow: "0 6px 24px rgba(17, 24, 39, 0.08)",
          fontFamily: "Pretendard, Noto Sans KR, -apple-system, BlinkMacSystemFont, Segoe UI, sans-serif",
        }}
      >
        <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center" }}>
          <div style={{ color: "#1E3A8A", fontSize: "18px", fontWeight: 700 }}>Exploon</div>
          <div style={{ display: "flex", gap: "8px", alignItems: "center" }}>
            <div
              style={{
                color: "#1E3A8A",
                background: "#EFF6FF",
                border: "1px solid #BFDBFE",
                borderRadius: "999px",
                padding: "4px 10px",
                fontSize: "12px",
                fontWeight: 700,
              }}
            >
              {data.documentType}
            </div>
            <div style={{ color: "#6B7280", fontSize: "13px" }}>{data.generatedAt}</div>
          </div>
        </div>

        <h2 style={{ marginTop: "20px", color: "#111827", fontSize: "30px", fontWeight: 700, lineHeight: 1.2 }}>
          문서 핵심 요약
        </h2>

        <p style={{ marginTop: "24px", color: "#111827", fontSize: "20px", lineHeight: 1.6, fontWeight: 600 }}>
          {data.coreSummary}
        </p>

        <div style={{ marginTop: "26px" }}>
          <div style={{ color: "#1E3A8A", fontWeight: 700, fontSize: "16px" }}>주요 포인트</div>
          <ul style={{ marginTop: "12px", color: "#374151", fontSize: "17px", lineHeight: 1.75, paddingLeft: "22px" }}>
            {data.points.slice(0, 5).map((point, idx) => (
              <li key={`${point}-${idx}`}>{point}</li>
            ))}
          </ul>
        </div>

        <div style={{ marginTop: "32px", borderTop: "1px solid #E5E7EB", paddingTop: "14px", color: "#6B7280", fontSize: "13px" }}>
          Generated by Exploon
        </div>
      </div>
    </div>
  );
}
