"use client";

import { CalendarClock } from "lucide-react";
import ResultCardCoverImage from "@/components/ResultCardCoverImage";
import ResultCardTextBlock from "@/components/ResultCardTextBlock";

export type ResultVisualCardData = {
  documentType: string;
  coreSummary: string;
  points: string[];
  conclusion: string;
  createdAt: string;
  coverImageUrl?: string;
};

function toDocumentTypeLabel(documentType: string): string {
  const map: Record<string, string> = {
    policy: "정책 문서",
    business_plan: "사업계획서",
    study_material: "시험 자료",
    news: "기사/보도자료",
    meeting_report: "회의/보고 문서",
    general: "일반 문서",
  };
  return map[documentType] ?? "일반 문서";
}

export default function ResultVisualCard({
  data,
  cardRef,
  compact = false,
}: {
  data: ResultVisualCardData;
  cardRef?: React.RefObject<HTMLDivElement | null>;
  compact?: boolean;
}) {
  return (
    <article
      ref={cardRef}
      className={[
        "mx-auto w-full max-w-[860px] overflow-hidden rounded-[24px] border border-[#DBE4FF]",
        "bg-gradient-to-b from-white to-[#F8FBFF]",
        "shadow-[0_20px_60px_rgba(37,99,235,0.08)]",
        compact ? "min-h-[440px] p-8" : "min-h-[480px] p-8 sm:p-10",
      ].join(" ")}
    >
      <header className="flex items-center justify-between gap-4">
        <div className="flex items-center gap-2">
          <div className="grid h-9 w-9 place-items-center rounded-lg bg-[#1E3A8A] text-sm font-bold text-white">E</div>
          <div className="text-base font-semibold text-[#111827]">Exploon</div>
        </div>
        <div className="rounded-full bg-[#EFF6FF] px-3 py-1 text-xs font-semibold text-[#1E3A8A]">
          {toDocumentTypeLabel(data.documentType)}
        </div>
      </header>

      <div className="mt-5">
        <ResultCardCoverImage documentType={data.documentType} coverImageUrl={data.coverImageUrl} />
      </div>

      <ResultCardTextBlock coreSummary={data.coreSummary} points={data.points} conclusion={data.conclusion} />

      <footer className="mt-6 flex items-center justify-between border-t border-[#E5E7EB] pt-4 text-xs text-[#6B7280]">
        <div className="inline-flex items-center gap-1.5">
          <CalendarClock size={13} />
          {data.createdAt}
        </div>
        <div>Generated by Exploon</div>
      </footer>
    </article>
  );
}
