"use client";

import { CalendarClock } from "lucide-react";

export type ResultImageCardData = {
  documentType: string;
  coreSummary: string;
  points: string[];
  conclusion: string;
  createdAt: string;
};

function toDocumentTypeLabel(documentType: string): string {
  const map: Record<string, string> = {
    policy: "정책 문서",
    business_plan: "사업계획서",
    study_material: "시험 자료",
    news: "기사/보도자료",
    meeting_report: "회의/보고 문서",
    general: "일반 문서",
  };
  return map[documentType] ?? "일반 문서";
}

export default function ResultImagePreviewCard({
  data,
  cardRef,
  compact = false,
}: {
  data: ResultImageCardData;
  cardRef?: React.RefObject<HTMLDivElement | null>;
  compact?: boolean;
}) {
  return (
    <article
      ref={cardRef}
      className={[
        "mx-auto w-full max-w-[860px] rounded-3xl border border-[#DBE4FF]",
        "bg-gradient-to-b from-white to-[#F8FBFF]",
        "shadow-[0_20px_60px_rgba(37,99,235,0.08)]",
        compact ? "min-h-[420px] p-8" : "min-h-[480px] p-8 sm:p-10",
      ].join(" ")}
    >
      <header className="flex items-center justify-between gap-4">
        <div className="flex items-center gap-2">
          <div className="grid h-9 w-9 place-items-center rounded-lg bg-[#1E3A8A] text-sm font-bold text-white">E</div>
          <div className="text-base font-semibold text-[#111827]">Exploon</div>
        </div>
        <div className="rounded-full bg-[#EFF6FF] px-3 py-1 text-xs font-semibold text-[#1E3A8A]">
          {toDocumentTypeLabel(data.documentType)}
        </div>
      </header>

      <section className="mt-7">
        <h3 className="text-3xl font-semibold tracking-tight text-[#111827]">문서 핵심 요약</h3>
        <p className="mt-4 line-clamp-5 text-lg font-medium leading-8 text-[#1F2937]">{data.coreSummary}</p>
      </section>

      <section className="mt-7">
        <div className="text-sm font-semibold text-[#1E3A8A]">주요 포인트</div>
        <ul className="mt-3 space-y-2.5">
          {data.points.slice(0, 5).map((point, idx) => (
            <li key={`${point}-${idx}`} className="flex items-start gap-2.5 text-[15px] leading-7 text-[#374151]">
              <span className="mt-2 h-1.5 w-1.5 rounded-full bg-[#1E3A8A]" />
              <span className="line-clamp-3">{point}</span>
            </li>
          ))}
        </ul>
      </section>

      <section className="mt-6 rounded-xl border border-[#E2E8F0] bg-white/70 px-4 py-3">
        <div className="text-xs font-semibold uppercase tracking-wide text-[#64748B]">한 줄 결론</div>
        <p className="mt-1 text-sm font-semibold leading-6 text-[#1E3A8A]">{data.conclusion}</p>
      </section>

      <footer className="mt-7 flex items-center justify-between border-t border-[#E5E7EB] pt-4 text-xs text-[#6B7280]">
        <div className="inline-flex items-center gap-1.5">
          <CalendarClock size={13} />
          {data.createdAt}
        </div>
        <div>Generated by Exploon</div>
      </footer>
    </article>
  );
}
